### ISSUE TITLE
Should we remove the FieldBuilder.BuildForType overload that takes a contract resolver?

### ISSUE THREAD

**Issue by idg10** [idg10/azure-sdk-for-net#16]
See comment at https://github.com/idg10/azure-sdk-for-net/commit/78b2d492a84d04940aaf3230adfc28dcdb735046#commitcomment-19326172

**Comment by bitsforthought** [comment]
Sorry for the confusion; I just meant don't mention `SearchServiceClient` in the comments. The overload that takes `IContractResolver` is still necessary for the case when you use a custom resolver with  `SearchIndexClient`.

I just realized we can't really cover the case where someone uses a custom `JsonConverter` instead of an `IContractResolver`, but there's not much we can do about that.

**Comment by bitsforthought** [comment]
@idg10 Just checking if you saw my response. We'd love to see your official PR whenever you're ready. :-)

**Comment by bitsforthought** [comment]
@idg10 We'll be preparing a release candidate for the next GA of the Search SDK within the next week or two. It would be great to have your PR before then.

**Comment by idg10** [comment]
Fixed comment as per @brjohnstmsft comment
